#!/usr/bin/env bash
# Reads config/runners.yml and generates docker-compose.yml for Linux runners
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

check_deps

linux_count="$(yq '[.runners[] | select(.os == "linux")] | length' "$CONFIG")"

if [[ "$linux_count" -eq 0 ]]; then
  echo "No Linux runners defined in $CONFIG"
  cat > "$COMPOSE_FILE" <<'EOF'
# AUTO-GENERATED by ./scripts/generate-compose.sh
# Source of truth: config/runners.yml — do not edit manually.
services: {}
EOF
  exit 0
fi

pat_var="$(yq '.github.pat_env_var' "$CONFIG")"

{
  cat <<EOF
# AUTO-GENERATED by ./scripts/generate-compose.sh
# Source of truth: config/runners.yml — do not edit manually.

services:
EOF

  volumes=()

  for i in $(seq 0 $((linux_count - 1))); do
    selector=".runners | map(select(.os == \"linux\")) | .[$i]"

    name="$(yq "$selector | .name" "$CONFIG")"
    repo="$(yq "$selector | .repo" "$CONFIG")"
    count="$(yq "$selector | .count // 1" "$CONFIG")"
    labels="$(yq "$selector | .labels | join(\",\")" "$CONFIG")"

    for n in $(seq 1 "$count"); do
      service_name="${name}-${n}"
      vol_name="${service_name}-work"
      volumes+=("$vol_name")

      cat <<EOF
  ${service_name}:
    build:
      context: ./docker
      args:
        RUNNER_VERSION: \${RUNNER_VERSION:-latest}
    image: gh-runner:local
    restart: unless-stopped
    environment:
      REPO_URL: https://github.com/${repo}
      ACCESS_TOKEN: \${${pat_var}}
      RUNNER_NAME: ${service_name}
      LABELS: ${labels}
      RUNNER_WORKDIR: _work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${vol_name}:/home/runner/_work
    security_opt:
      - label:disable

EOF
    done
  done

  if [[ ${#volumes[@]} -gt 0 ]]; then
    echo "volumes:"
    for v in "${volumes[@]}"; do
      echo "  ${v}:"
    done
  fi

} > "$COMPOSE_FILE"

total_services="${#volumes[@]}"
echo "Generated $COMPOSE_FILE ($linux_count runner group(s), $total_services service(s))"
