baseURL = "https://an-lee.github.io/gh-sr/"
languageCode = "en-us"
title = "Self-hosted runner manager for GitHub"
theme = "book"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookRepo = "https://github.com/an-lee/gh-sr"
  BookEditPath = "edit/main/docs/content"
  BookSection = "/"
