name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: [self-hosted, linux, ci]
    steps:
      - uses: actions/checkout@v6

      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
          build_script_override: scripts/gh-extension-release-build.sh
